ServerEvents.recipes(event => {
   event.remove({ id: 'tiab:time_in_a_bottle' })
   event.remove({ id: 'catburger:cat_burger' })
   event.remove({ id: 'endrem:undead_eye' })
   event.remove({ id: 'minecraft:chainmail_helmet' })
   event.remove({ id: 'minecraft:chainmail_boots' })
   event.remove({ id: 'minecraft:chainmail_leggings' })
   event.remove({ id: 'minecraft:chainmail_chestplate' })
   event.remove({ id: 'bagofholding:golden_bag_of_holding' })
   event.remove({ id: 'bagofholding:iron_bag_of_holding' })
   event.remove({ id: 'bagofholding:leather_bag_of_holding' })
   event.remove({ id: 'jaffactory:jaffa_cake' })
   event.remove({ id: 'jaffactory:orange_juice' })
   event.remove({ id: 'jaffactory:jaffa_base' })
   event.remove({ id: 'jaffactory:jaffa_slime_base' })
   event.remove({ id: 'explorerscompass:explorers_compass' })
})